import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth, signInWithPopup, GoogleAuthProvider } from 'firebase/auth';

// We import the config generated by AI Studio
import config from '../firebase-applet-config.json';

export const app = initializeApp(config);
export const db = getFirestore(app, (config as any).firestoreDatabaseId);
export const auth = getAuth(app);

const provider = new GoogleAuthProvider();

export const login = () => signInWithPopup(auth, provider);
